// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwokNtyPti2VFBRe0WlP4G6MLevB6Qsbc',
    appId: '1:97471154968:web:796a62bd9228e07a0e6c6d',
    messagingSenderId: '97471154968',
    projectId: 'firebase-todo-adityandar',
    authDomain: 'fir-todo-adityandar.firebaseapp.com',
    storageBucket: 'firebase-todo-adityandar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxOiEXKnR98VVhOl5vQaOQKJv9gLR1wQk',
    appId: '1:97471154968:android:b5d93d4bf7705d020e6c6d',
    messagingSenderId: '97471154968',
    projectId: 'firebase-todo-adityandar',
    storageBucket: 'firebase-todo-adityandar.appspot.com',
  );
}
